### ISSUE TITLE
 Connection closed with reason: connection failed (1006)

### ISSUE THREAD

**Issue by xvilo** [Lemmmy/rocketchat-bot#1]
When trying to run example. All details are verified and correct.

```
$ node example.js
(node:3972) UnhandledPromiseRejectionWarning: Error: Connection closed with reason: connection failed (1006)
    at WebSocketAsPromised._handleClose (/Users/xvilo/projects/rocketchat-bot/node_modules/websocket-as-promised/lib/index.js:207:19)
    at W3CWebSocket.<anonymous> (/Users/xvilo/projects/rocketchat-bot/node_modules/websocket-as-promised/lib/index.js:103:26)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/xvilo/projects/rocketchat-bot/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (/Users/xvilo/projects/rocketchat-bot/node_modules/websocket/lib/W3CWebSocket.js:219:14)
    at WebSocketClient.<anonymous> (/Users/xvilo/projects/rocketchat-bot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
    at emitOne (events.js:116:13)
    at WebSocketClient.emit (events.js:211:7)
    at ClientRequest.handleRequestError (/Users/xvilo/projects/rocketchat-bot/node_modules/websocket/lib/WebSocketClient.js:215:14)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
(node:3972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:3972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Lemmmy** [comment]
Have you made sure that your connection URL is correct, and supports HTTPS?

**Comment by xvilo** [comment]
yes. Like I checked, it's all correct

**Comment by Lemmmy** [comment]
And are you able to open a regular websocket connection to `wss://your.rocket.chat/websocket`?

**Comment by xvilo** [comment]
yes

**Comment by AFIDclan** [comment]
Be sure you have no prefix on the url. It is added later:
` uri: '${opts.scheme}://${opts.server}${opts.endpoint}login',`

**Comment by Lemmmy** [comment]
I'm closing this issue under the assumption that @AFIDclan's suggestion is correct - feel free to reopen if it still persists even with no scheme on the URL.
